name: Master workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build and publish with Maven
      run: |
        chmod +x src/main/java/build/create-semver.sh
        VERSION=$(src/main/java/build/create-semver.sh pom.xml "${{github.run_number}}")
        mvn -B versions:set -DnewVersion="${VERSION}" --file pom.xml
        mvn -B package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
